### ISSUE TITLE
Missing "On Air" functionality

### ISSUE THREAD

**Issue by helo-head** [helo-head/Tally-Core2#10]
Consideration of "On Air" functionality. 

It looks like the **ATEMstd** library has a public method that can return "On Air" status (getKeyerOnAirEnabled). My hope is this will work as intended, otherwise I will have to replicate the changes AronHetLam made to his version of the ATEMmin library. My preference is to use an existing method where possible. 

The reason I cannot just substitute libraries is that the ATEMmin does not support some of the calls Im making.

**Comment by brianteeman** [comment]
getKeyerOnAirEnabled is not the same thing - thats for chroma key

The record and stream are not in the existing atem libraries

Can you not just copy his changes in ATEMmin into ATEMstd? Looks like he commented his code blocks so you can find the changes

**Comment by helo-head** [comment]
Yep, Im slow but I get there eventually. ... It just finished compiling so in theory I got the required changes correct :)
