### ISSUE TITLE
Move "On Air" functionality to configuration file

### ISSUE THREAD

**Issue by helo-head** [helo-head/Tally-Core2#12]
Although the ATEM mini is no longer sold, a lot of them exist in the wild. As the intent of the configuration file was to avoid having to hard-code ATEM features/settings in the code, I'm not sure hard coding OAS support was the right way to go. 

Since OAS is an ATEM feature and has little to do with the Core2 Im of the current opinion this maybe this should  move to the configuration file.

**Comment by brianteeman** [comment]
As you have designed this to support multiple configurations then you are correct and its probably a good idea to set OAS enable/disable in the config

**Comment by helo-head** [comment]
Did you ever get a chance to check the OAS config file functionality?

**Comment by brianteeman** [comment]
sorry for the incredibly slow reply. yes the oas indicator works!!
