### ISSUE TITLE
M5Core2 Library 0.0.3 Issue

### ISSUE THREAD

**Issue by helo-head** [helo-head/Tally-Core2#4]
Does not compile with Version 0.0.3 of the M5Stack M5Core2 Library  ... You must currently use 0.0.2

**Comment by brianteeman** [comment]
as the current version is 0.1.4 I assume this is no longer relevant?

**Comment by helo-head** [comment]
I confess I have not tried to recompile it since last year due to all the M5Stack library issues. If you find an a set of libraries that work reliably let me know and we can update this comment /and/or readme and add any specific instructions needed to get it to compile.

**Comment by brianteeman** [comment]
yeah - so far no luck at all getting this code to compile. I'm very new to this (but not development)

**Comment by brianteeman** [comment]
So I found the "problem". Basically you  need to be using Button instead of TouchButton

I was in the process of starting to convert everything when I stumbled across https://github.com/kitazaki/M5Core2_atemswitcher

This is a fork of @aaronpk code to work with the newer m5 libraries. It said it was only tested with 0.0.6 but I just compiled it without error on 0.1.5 so I assume the lbraries have not changed for this part at least since then.

Not tested it on the actual atem yet as that's in another building but the fact it compiles gives me hope.

**Comment by helo-head** [comment]
As you figured out, the TouchButton type was dropped from the M5Core2 Touch library in 0.0.3 with no documentation other than a single  note on GitHub in the M5Touch.h header that refers to a **Legacy API.** Unfortunately even the header **incorrectly** states the "This older API is still supported". Many thanks for opening a bug against M5Core2. These types of issues are why I stopped updating the code last year. 

The good news I was able to validate the code  does compile and work using:

 Arduino IDE 1.18.13 / M5Stack Board 1.0.7 / M5Core2 Library 0.0.2

Of course I understand this is not a desirable outcome, as such I will take a closer look and see what it will take to update the code to the new Touch library.

**Comment by brianteeman** [comment]
> Not tested it on the actual atem yet as that's in another building but the fact it compiles gives me hope.

Tested that one now and as soon as I remembered to modify the atem libraries as they stated it worked

**Comment by brianteeman** [comment]
Progress so far in converting your script. https://gist.github.com/brianteeman/30447842f7b3c07a091a753cc57a6a36

now to look at the sd card code so I can actually test this

**Comment by helo-head** [comment]
Ah, looks like we started working on this at the same time. Im finished with the required changes however I have run into an issue with "I2S Port 0 not installed". As my Core2 was previously used for testing it still had a config stored in NVM so at least Im not dead in the water. Now I just need to borrow an ATEM for testing as well as try and figure out whats going on the I2S system.

**Comment by brianteeman** [comment]
sounds like it could be an issue with the drivers on your  computer and not the Core2.

Would be good to see your code as I am working kind of blind and guessing what it is supposed to do whereas you know what it is supposed to do as you wrote it.

**Comment by helo-head** [comment]
Try the attached, In theory it should work. I had to add a quick hack to the readSDconfig function since cfg.begin  apparently now requires the full path even if the file resides in the root. If it works let me know and Ill start cleaning it up before I upload it. 

[Tallly-Core2-V10B.txt](https://github.com/helo-head/Tally-Core2/files/10524426/Tallly-Core2-V10B.txt)

**Comment by helo-head** [comment]
At some point **past** IDE 1.8.13 the  SD File name() or possibly openNextFile()  function was changed so that the name returned no longer includes the full path when dealing with the root directory  This is why the SDConfigFile.begin() code was failing on the subsequent call to SD.open. Apparently SD.open always required the full path which should not be case when dealing with the root directory. I would not have figured this out had I not taken a look at the screen shots from version 1.0 that showed the fully qualified names. 

Ill ping the developer and see what he thinks about both issues . In the mean time my hack seems to work as a quick fix until I can determine the best way to correctly address this issue.

**Comment by brianteeman** [comment]
didnt have a chance to look at anything today. But I brought the atem to my home office so will check out your script tomorrow.

**Comment by brianteeman** [comment]
Great news. It works.

Now I can start customising it for my own purposes. ~The first step of which is to remove alll the very clever config stuff you wrote and replace it with hard coded values. I understand why you did it that way but it is overkill for my usecase and it requires so much code to maintain~

**Comment by helo-head** [comment]
I started the same way, however within a month of the first ATEM purchase the company opted to expand to several thus the reason for the SD card allowing easy reconfiguration. However leaving SD cards around with sensitive info seemed inappropriate thus the reason for writing the config data in flash allowing us to keep the SD cards in a secure location until needed for a reconfiguration.  At last check they expanded the fleet even more with some of the newer models.

**Comment by brianteeman** [comment]
yes I changed my mind.

such a shame that the skaarhoj library stopped at 7.5 and that the replacement opensource library (libatem) is in c# not c++

**Comment by helo-head** [comment]
Before uploading the latest version I want to ensure that the SD Library (Version 2.0.0) that now ships with M5Ccore2 Board 2.0.6 is behaving correctly when using the file.name function. I cannot find any documentation for the SD Libraries I have looked at thus far that explain why the SD Library dropped the root path between versions 1.0.5 and 2.0.0. Once I know if the new behavior is correct/incorrect I will rewrite the code appropriate to the expected behavior. 

PS: Thanks for motivating me to finally address this issue.

**Comment by brianteeman** [comment]
> Thanks for motivating me to finally address this issue.

It is me that should be saying thanks

**Comment by helo-head** [comment]
It appears that the ESP32 SD & FS libraries were significantly changed in release 2.0.0. The good news is they decided to add a FS::path() method  which gives the original FQN behavior as in release 1.0.5. Ive included the reference.

https://github.com/espressif/arduino-esp32/pull/4892

Ill make the appropriate change  and upload the updated code most likely tomorrow.

**Comment by helo-head** [comment]
This should be the final version. I found a newer version where I had apparently moved the location of the battery icon. If you prefer the older battery icon location  let me know and I will move it back.

[Tallly-Core2-V10B.txt](https://github.com/helo-head/Tally-Core2/files/10531306/Tallly-Core2-V10B.txt)

**Comment by brianteeman** [comment]
I am smiling. The first thing I had done was to move the battery icon to the top (and remove the voltage display).

Not sure if the following is a logic error or not and also not sure if it is worth fixing but.

boot with the atem on then the connection status dot will display as green ✔️
change the atem to off and the connection status diot will display red ✔️
change the atem to off and the connection status diot will display green✔️

BUT
boot with the atem off then the connection status dot will not display at all (until a conection is established)
I had expected in this case for it to show red

I am assuming that this is due to the code beginning at line 1150

**Comment by helo-head** [comment]
The test for network status change based on change of state was done to limit screen updates which were causing performance issues. It comes at a cost of not necessarily seeing what you expect until you get a valid response to the isConnected helo packet.

With all that said, it would not be that hard to show the default disconnected state on first pass. Ill have to think about the best way to do this. You will have to be my guinea  pig as I don't have access to an ATEM anymore.

**Comment by helo-head** [comment]
Try the following. I now display a initial lightgray "pre-connection" dot  to differentiate it from a disconnect. I also opted to display the battery status during the setup  just to ensure it shows up in case there are network issues after setup finishes. 

I guess I need to update the docs as well to correctly show the new icons locations and colors. 

[Tallly-Core2-V10B.txt](https://github.com/helo-head/Tally-Core2/files/10538687/Tallly-Core2-V10B.txt)

**Comment by brianteeman** [comment]
tested and works as intended.

**Comment by helo-head** [comment]
Here is the new documentation to go along with it including new graphics (hopefully correct).

[Tally-Core2-UserGuide.pdf](https://github.com/helo-head/Tally-Core2/files/10539505/Tally-Core2-UserGuide.pdf)

**Comment by helo-head** [comment]
Closed with release 1.1
